services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: yassinaboelnaga/prodml-api:0.1.0
    ports:
      - "8000:8000"
    environment:
      - PRODML_MODEL_PATH=/app/models/model.pkl
    volumes:
      - ../models:/app/models
    restart: unless-stopped
